version = 0.1

[default.global.parameters]
stack_name = "aws-sam-cli-managed-default"
region = "us-west-1"

[default.build.parameters]
cached = true
parallel = true
use_container = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "sam-artifacts"
parameter_overrides = [
  "DbUrl=\"${DB_URL}\"",
  "S3BucketName=\"${AWS_S3_BUCKET}\""
]
