version = 0.1

[default.global.parameters]
stack_name = "groovonomy-infrastructure"

[default.build.parameters]
cached = true
parallel = true
use_container = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
stack_name = "groovonomy-infrastructure"
confirm_changeset = false
s3_prefix = "bandify"
parameter_overrides = "DbUrl=\"${DB_URL}\" S3BucketName=\"${AWS_S3_BUCKET}\""
image_repositories = []
