AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  SAM Template for SearchResults API deployment

Parameters:
  DbUrl:
    Type: String
    Description: The full connection URL for the Postgres DB

  S3BucketName:
    Type: String
    Description: Name of the S3 bucket this Lambda function will access

Globals:
  Function:
    Timeout: 3
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
    Tags:
      Project: Groovonomy
      Environment: Production

  Api:
    TracingEnabled: true

Resources:
  SearchResultsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:log-group:/aws/lambda/*
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${S3BucketName}
                  - !Sub arn:aws:s3:::${S3BucketName}/*

  SearchResultsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: db_results/
      Handler: app.lambda_handler
      Runtime: python3.11
      Timeout: 30
      MemorySize: 512
      Role: !GetAtt SearchResultsExecutionRole.Arn
      Events:
        ApiEndpoint:
          Type: Api
          Properties:
            Path: /db_results
            Method: post
      Environment:
        Variables:
          DB_URL: !Ref DbUrl
      Tags:
        FunctionPurpose: SearchResults

Outputs:
  SearchResultsApi:
    Description: API Gateway endpoint URL for Prod stage for Search Results function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/db_results/"

  SearchResultsFunction:
    Description: Search Results Lambda Function ARN
    Value: !GetAtt SearchResultsFunction.Arn

  SearchResultsFunctionIamRole:
    Description: Custom IAM Role used by Search Results function
    Value: !GetAtt SearchResultsExecutionRole.Arn
