AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  SAM Template for SearchResults API deployment

Parameters:
  DbUrl:
    Type: String
    Description: The full connection URL for the Postgres DB

Globals:
  Function:
    Timeout: 3
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:
  # Custom IAM Role for Lambda
  SearchResultsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: search-results-exec-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource: "*"

  # Lambda Function with Explicit Role
  SearchResultsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: db_results/
      Handler: app.lambda_handler
      Runtime: python3.11
      Timeout: 30
      MemorySize: 512
      Role: !GetAtt SearchResultsExecutionRole.Arn
      Events:
        ApiEndpoint:
          Type: Api
          Properties:
            Path: /db_results
            Method: post
      Environment:
        Variables:
          DB_URL: !Ref DbUrl

  # Monitoring Resources
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  SearchResultsApi:
    Description: API Gateway endpoint URL for Prod stage for Search Results function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/db_results/"
  SearchResultsFunction:
    Description: Search Results Lambda Function ARN
    Value: !GetAtt SearchResultsFunction.Arn
  SearchResultsFunctionIamRole:
    Description: Custom IAM Role used by Search Results function
    Value: !GetAtt SearchResultsExecutionRole.Arn