name: Build and Test React Application

on:
  push:
    branches: [ 'dev', 'main' ]
  pull_request:
    branches: [ 'dev', 'main' ]

defaults:
  run:
    working-directory: ./frontend

permissions:
  id-token: write
  contents: read

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
          
      - name: Print GitHub Context
        run: |
              echo "GITHUB_REF: $GITHUB_REF"
              echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"

      - name: Set AWS role ARN
        run: echo "ROLE_ARN=arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubOIDCFrontendDeployRole" >> $GITHUB_ENV

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: npm ci, build and test
        run: |
          npm ci
          npm run build --if-present
          # npm test
