name: Build and Deploy SAM with Poetry

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./backend/infrastructure/.aws-sam

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2
      
      # Export dependencies for Playwright Lambda Function

      - name: Export Playwright dependencies
        run: |
          poetry export -f requirements.txt --without-hashes --with playwright -o playwright_function/requirements.txt
        working-directory: backend/infrastructure

      # Export dependencies for SearchResults Lambda Function

      - name: Export SearchResults dependencies
        run: |
          poetry export -f requirements.txt --without-hashes -o search_results/requirements.txt
        working-directory: backend/infrastructure

      # Set up AWS SAM CLI

      - name: Set up AWS SAM
        uses: aws-actions/setup-sam@v1

      # Configure AWS Credentials

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubOIDCSAMDeployRole
          aws-region: ${{ secrets.AWS_REGION }}

      # Build SAM apps
      
      - name: Build Playwright stack
        run: sam build --template-file playwright/template-playwright.yaml --use-container

      - name: Build SearchResults stack
        run: sam build --template-file search_results/template-searchresults.yaml --use-container


      # Playwright stack deploy

      - name: Deploy Playwright Stack
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          sam deploy \
            --template-file playwright/template-playwright.yaml \
            --stack-name playwright-stack \
            --region $AWS_REGION \
            --capabilities CAPABILITY_IAM \
            --s3-bucket $AWS_S3_BUCKET \
            --s3-prefix sam-artifacts/playwright \
            --parameter-overrides S3BucketName=$AWS_S3_BUCKET \
            --no-confirm-changeset

      - name: Dump Playwright stack events
        run: |
          aws cloudformation describe-stack-events \
            --stack-name PlaywrightStack \
            --region ${{ secrets.AWS_REGION }} \
            --max-items 20

      # SearchResults stack deploy

      - name: Deploy SearchResults Stack
        env:
          DB_URL: ${{ secrets.DB_URL }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          sam deploy \
            --template-file search_results/template-searchresults.yaml \
            --stack-name searchresults-stack \
            --region $AWS_REGION \
            --capabilities CAPABILITY_IAM \
            --s3-bucket $AWS_S3_BUCKET \
            --s3-prefix sam-artifacts/searchresults \
            --parameter-overrides DbUrl=$DB_URL S3BucketName=$AWS_S3_BUCKET \
            --no-confirm-changeset

      - name: Dump SearchResults Stack Events
        run: |
          aws cloudformation describe-stack-events \
            --stack-name SearchResultsStack \
            --region ${{ secrets.AWS_REGION }} \
            --max-items 20
